<h2 class="text-center">Softjourn Info TV Playlist</h2>
<div class="userLogin">
    Welcome, {{ login }}! <a href="login/logout">Log out</a>
</div>
<label>
    Show Random
    <input type="checkbox" {% if order == 'random' %} checked="checked" {% endif %} data-toggle="toggle"
           id="plOrder"
           class="plOrder" name="order"/>
    &nbsp;&nbsp;&nbsp;
</label>
<div class="btn-group">
    <button type="button" id="dLabel" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
        add item <span class="caret"></span>
    </button>
    <ul class="dropdown-menu addItem" aria-labelledby="dLabel">
        <li><a href="#" data-toggle="modal" data-backdrop="static" data-target="#addImage">Image</a></li>
        <li><a href="#" data-toggle="modal" data-backdrop="static" data-target="#addYoutube">Youtube</a></li>
    </ul>
</div>
<div class="btn-group playlistOptions">
    <form action="index/updateConfig" method="post">
        Default duration: <input type="number" name="defaultDuration" value="{{ defaultDuration }}"
                                 class="durationInput plDuration" min="1" max="600">s
    </form>
</div>


<div class="container-fluid clearBoth">
    <div class="row playlist">
        {% for item in items %}
            {{ partial("partial/item", item) }}
        {% endfor %}
    </div>
</div>


<div class="modal fade" id="addImage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Image</h4>
            </div>
            <div class="modal-body">
                <form id="imageUploadForm" action="index/addImage" method="POST" enctype="multipart/form-data">
                    <input type="file" name="newImage" id="newImage">
                    <div class="newImageDurationDiv">Duration:
                        <input type="number" class="durationInput" min="1" name="newImageDuration" size="2">s
                    </div>
                    <div class="form-group item-time">
                        <strong>Time:</strong><br>
                        From <input type="text" class="timepicker form-control" name="startTime"/>
                        to <input type="text" class="timepicker form-control" name="endTime"/>
                    </div>
                    <div class="form-group item-date">
                        <strong>Date:</strong><br>
                        From <input type="text" class="form-control datepicker" name="startDate">
                        to <input type="text" class="form-control datepicker" name="endDate">
                    </div>
                </form>
                <img id="addImagePreview"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary submitItem">Add</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addYoutube" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Youtube video</h4>
            </div>
            <div class="modal-body">
                <form id="videoUploadForm" action="index/addYoutube" method="POST" class="form-group">
                    <input type="text" name="youtubeURL" class="form-control" placeholder="Video URL">
                    <br>
                    <label for="volumeLevel">Volume Level</label>
                    <input type="range" min="0" max="100" step="1" name="volumeLevel" id="volumeLevel"/>
                    <div class="form-group item-time">
                        <strong>Time:</strong><br>
                        From <input type="text" class="timepicker form-control" name="startTime"/>
                        to <input type="text" class="timepicker form-control" name="endTime"/>
                    </div>
                    <div class="form-group item-date">
                        <strong>Date:</strong><br>
                        From <input type="text" class="form-control datepicker" name="startDate">
                        to <input type="text" class="form-control datepicker" name="endDate">
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary submitItem">Add</button>
            </div>
        </div>
    </div>
</div>

<script>
    var $playlist = $('.playlist');

    function makeGallery(item) {
        if ($playlist.data('lightGallery')) {
            $playlist.data('lightGallery').destroy(true);
        }
        $playlist.lightGallery(
            {
                selector: '.gallery'
            }
        );
    }

    function setAjaxForm(form) {
        if (!form) {
            form = $('form')
        }
        form.ajaxForm(function (res) {
            $.notify(res.message, res.status);
            if (res.item) {
                $playlist.prepend(res.item);
                var newItem = $playlist.first(), newForm = newItem.find('form');
                setAjaxForm(newForm);
                makeGallery();
                initItemDateAndTimePicker(res.itemData);
            }
        });
    }

    function initItemDateAndTimePicker(itemData) {

        $('#' + itemData.id +' .timepicker').timepicker({
            selectOnBlur: true,
            timeFormat: 'H:i',
            step: 15
        });

        $('#' + itemData.id +' .datepicker').datepicker({
            autoclose: true,
            format: "dd:mm:yyyy"
        });
        $('#' + itemData.id +' .datepicker[name=startDate]').datepicker('setDate', itemData.startDate);
        $('#' + itemData.id +' .datepicker[name=endDate]').datepicker('setDate', itemData.endDate);
        $('#' + itemData.id +' .datepicker[name=startTime]').datepicker('setDate', itemData.startTime);
        $('#' + itemData.id +' .datepicker[name=endTime]').datepicker('setDate', itemData.endTime);
    }

    $('.submitItem').on('click', function (e) {
        var $this = $(this), modal = $this.parents('.modal'), form = modal.find('form');
        modal.modal('hide');
        form.submit();
        form[0].reset();
        $('#addImagePreview').hide();
    });

    $('#newImage').on('change', function (e) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#addImagePreview')
                .attr('src', e.target.result)
                .css({display: "block", height: "200px"});
        };
        reader.readAsDataURL(e.target.files[0]);
    });

    $playlist.on('click', '.removeItem', function (e) {
        if (confirm('Are you sure?')) {
            var $this = $(this), id = $this.parents('.listItem').attr('data-id');
            $.getJSON('index/removeItem/' + id, function (res) {
                $.notify(res.message, res.status);
                if (res.status == 'success') {
                    $this.parents('.listItem').parent().remove();
                }
            });
        }
        return false;
    });
    $playlist.on('click', '.itemSettings', function (e) {
        $(this).parents('.listItem').find('.settings').toggleClass('hidden');
        return false;
    });
    $playlist.on('blur', '.updateItem', function (el) {
        $(this).parents('form').submit();
    });
    $('.plDuration').on('blur', function (el) {
        $(this).parents('form').submit();
    });
    $('#plOrder').on('change', function (el) {
        $.post(
            'index/updateConfig/',
            {
                order: $(this).prop('checked')
            },
            function (res) {
                $.notify(res.message, res.status);
            });
    });

    $('.timepicker').timepicker({
        selectOnBlur: true,
        timeFormat: 'H:i',
        step: 15
    });

    $('.datepicker').datepicker({
        autoclose: true,
        format: "dd:mm:yyyy"
    });

    {{ partial("partial/init_datetime", items) }}

    $(document).ready(function () {
        setAjaxForm();
        makeGallery();
    });

</script>