<div class="tvLogin">
    <div class="tvLogo">
        <i class="fa fa-television sjtv"></i>
        <img src="img/sj_logo.png">
    </div>
    <form class="form-horizontal" role="form" action="" method="post">
        {% if error is defined %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            {{ error }}
        </div>
        {% endif %}
        <div class="form-group">
            <label for="login" class="col-sm-3 control-label">Login:</label>

            <div class="col-sm-9">
                <input type="text" name="login" class="form-control" id="login" value="{% if login is defined  %}{{ login }}{% endif %}">
            </div>
        </div>

        <div class="form-group">
            <label for="password" class="col-sm-3 control-label">Password:</label>

            <div class="col-sm-9">
                <input type="password" name="password" class="form-control" id="password">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-success btn-block">Login</button>
            </div>
        </div>
    </form>

</div>