<!DOCTYPE html>
<html lang="en">
<head>
    <title>Softjourn TV playlist</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="{{ serverHome }}">
    <link rel="icon" href="favicon.ico">
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="lib/bootstrap/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link href="lib/bootstrap/css/bootstrap-datepicker.css" rel="stylesheet">
    <link href="lib/timepicker/css/jquery.timepicker.css" rel="stylesheet">
    <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="css/styles.css?v=1.1" rel="stylesheet">
    <script src="lib/jquery-1.11.3.min.js"></script>
    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/bootstrap/js/bootstrap-toggle.min.js"></script>
    <script src="lib/bootstrap/js/bootstrap-datepicker.js"></script>
    <script src="lib/timepicker/js/jquery.timepicker.js"></script>
    <script src="lib/datepair/datepair.js"></script>
    <script src="lib/notify.min.js"></script>
    <script src="lib/jquery.form.min.js"></script>
    <script src="lib/lightGallery/js/lightgallery.min.js"></script>
    <link type="text/css" rel="stylesheet" href="lib/lightGallery/css/lightgallery.min.css" />

</head>
<body>
<div class="content">
{{ content() }}
</div>
</body>
</html>